### ISSUE TITLE
No Message Configuration

### ISSUE THREAD

**Issue by hcostanzo** [tiberiuzuld/angular-busy#10]
I would like to have just an icon spinner and no "Please Wait" message. Can these configurations be added to easily customize the spinner?

**Comment by tiberiuzuld** [comment]
You can use custom template or empty string message
Look at the demo page.

**Comment by hcostanzo** [comment]
template: '<div id="loader-wrapper"><div id="loader"></div><div class="loader-section section-left"></div><div class="loader-section section-right"></div></div>',

Does this as just template instead of templateRef work? I have a larger app and wanting to configure this once in the forRoot. I didn't see how a templateRef could be referenced in the AppModule

**Comment by hcostanzo** [comment]
I looked at the template options, but trying to set this up once in AppModule to use in several places in the app. How is this template setup in an AppModule .forRoot configuration?

**Comment by tiberiuzuld** [comment]
https://github.com/tiberiuzuld/angular-busy#overriding-defaults
