### ISSUE TITLE
Caching with ForkJoin Issue

### ISSUE THREAD

**Issue by jsmith39** [tiberiuzuld/angular-busy#3]
Thanks for migrating this busy indicator to the latest angular version.  I've been using cgBusy and its variants for a long time.

I've found an issue with it:  when a forkJoin is used and all observables are returned immediately (client side caching in this case) and it errors out with the following.

ERROR TypeError: Unable to get property 'unsubscribe' of undefined or null reference

The error happens within cgBusy.service.ts.  On line #37 (inside the callThen function) is where the error actually happens.  As you would expect subscription is undefined line #37 is below:

subscription.unsubscribe();

The reason it is happening is because both of my services get cached and then they return immediately.  When they return immediately, line# 37 executes before execution of line #40 finishes.  When I return the values immediately, I'm using the "of" RXjs operator.

If you need anything else let me know,

**Comment by tiberiuzuld** [comment]
Hi @jsmith39 ,
It should be fixed now in v8.0.1
