### ISSUE TITLE
How to set the templateRef property for the module?

### ISSUE THREAD

**Issue by deyvidfk** [tiberiuzuld/angular-busy#8]
How to set the **templateRef** property for the module?

```ts
import {CgBusyModule} from 'angular-busy2';

@NgModule({
 imports: [
     CgBusyModule.forRoot({
         templateRef: ???
     }) 
 ]
});
```

**Comment by tiberiuzuld** [comment]
Hi @deyvidfk ,
You need to override defaults like in readme.md 
For template the only option is from component 
https://github.com/tiberiuzuld/angular-busy#overriding-defaults
