### ISSUE TITLE
Angular 9 Support ?

### ISSUE THREAD

**Issue by flipZomb** [tiberiuzuld/angular-busy#9]
I tried to update my project to Angular 9, but without having examined in too much depth, seemed to be having issues with angular-busy. For the time being canceled the update to Angular 9. Should anguler-busy work under Angular9 and/or are plans for a new version available?

**Comment by tiberiuzuld** [comment]
Hi @flipZomb ,
Sorry for the delay caused by me not updating the library to latest angular.

I updated now the library to angular 9 and fixed the issues.
Please let me know if it works for you.

Thank you

**Comment by flipZomb** [comment]
Awesome !! Thank you so much for doing this so quickly.
